In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

In [2]:
df = pd.read_csv('countvec.csv')

In [3]:
df.head()

,title,text,date,source,author,category,label
0,Foreign Democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,real
1,To offer down resource great point.,probably guess western behind likely next inve...,2022-05-25,Fox News,Joseph Hill,Politics,fake
2,Himself church myself carry.,them identify forward present success risk sev...,2022-09-01,CNN,Julia Robinson,Business,fake
3,You unit its should.,phone which item yard Republican safe where po...,2023-02-07,Reuters,Mr. David Foster DDS,Science,fake
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,2023-04-03,CNN,Austin Walker,Technology,fake

In [4]:
df = df.drop(columns='date')

In [5]:
df.head()

,title,text,source,author,category,label
0,Foreign Democrat final.,more tax development both store agreement lawy...,NY Times,Paula George,Politics,real
1,To offer down resource great point.,probably guess western behind likely next inve...,Fox News,Joseph Hill,Politics,fake
2,Himself church myself carry.,them identify forward present success risk sev...,CNN,Julia Robinson,Business,fake
3,You unit its should.,phone which item yard Republican safe where po...,Reuters,Mr. David Foster DDS,Science,fake
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,CNN,Austin Walker,Technology,fake

In [6]:
# x = df.drop(columns = "label")
# y = df.label

In [7]:
df['sentence']=df['title']+df['text']

In [8]:
x=df['sentence']
y=df['label']

In [9]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.8, random_state = 42)

In [10]:
vectorizer = CountVectorizer(binary=False)

In [11]:
pipeline = Pipeline(steps = [("model",CountVectorizer(binary=False))] )

In [12]:
# pipeline = Pipeline(steps=[("vectorizer", CountVectorizer(binary=False)),("classifier", LogisticRegression())])
pipeline = Pipeline(steps=[("vectorizer", CountVectorizer(binary=False)),("classifier", DecisionTreeClassifier())])

In [13]:
pipeline.fit(xtrain,ytrain)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('classifier', DecisionTreeClassifier())])

In [14]:
abc=pipeline.fit(xtrain,ytrain)

In [15]:
# abc=pipeline.fit(xtrain['senetence'])

In [16]:
# abc.toarray()

In [17]:
vectorizer.fit(xtrain,ytrain)

CountVectorizer()

In [18]:
vect = vectorizer.fit_transform(xtrain)
vect.toarray()

array([[0, 0, 0, ..., 1, 0, 1],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4000, 969))

In [19]:
words = vectorizer.get_feature_names_out()

In [20]:
ypred = pipeline.predict(xtrain)

In [21]:
ypred_test=pipeline.predict(xtest)

In [22]:
print(words)

['ability' 'able' 'about' 'above' 'accept' 'according' 'account' 'across'
 'act' 'action' 'activity' 'actually' 'add' 'address' 'administration'
 'admit' 'adult' 'affect' 'after' 'again' 'against' 'age' 'agency' 'agent'
 'ago' 'agree' 'agreement' 'ahead' 'air' 'all' 'allow' 'almost' 'alone'
 'along' 'already' 'also' 'although' 'always' 'american' 'among' 'amount'
 'analysis' 'and' 'animal' 'another' 'answer' 'any' 'anyone' 'anything'
 'appear' 'apply' 'approach' 'area' 'argue' 'arm' 'around' 'arrive' 'art'
 'article' 'artist' 'as' 'ask' 'assume' 'at' 'attack' 'attention'
 'attorney' 'audience' 'author' 'authority' 'available' 'avoid' 'away'
 'baby' 'back' 'bad' 'bag' 'ball' 'bank' 'bar' 'base' 'be' 'beat'
 'beautiful' 'because' 'become' 'bed' 'before' 'begin' 'behavior' 'behind'
 'believe' 'benefit' 'best' 'better' 'between' 'beyond' 'big' 'bill'
 'billion' 'bit' 'black' 'blood' 'blue' 'board' 'body' 'book' 'born'
 'both' 'box' 'boy' 'break' 'bring' 'brother' 'budget' 'build' 'building'
 'business' 'but' 'buy' 'by' 'call' 'camera' 'campaign' 'can' 'candidate'
 'capital' 'car' 'card' 'care' 'career' 'carry' 'case' 'catch' 'cause'
 'cell' 'center' 'central' 'century' 'certain' 'certainly' 'chair'
 'challenge' 'chance' 'change' 'character' 'charge' 'check' 'child'
 'choice' 'choose' 'church' 'citizen' 'city' 'civil' 'claim' 'class'
 'clear' 'clearly' 'close' 'coach' 'cold' 'collection' 'college' 'color'
 'commercial' 'common' 'community' 'company' 'compare' 'computer'
 'concern' 'condition' 'conference' 'congress' 'consider' 'consumer'
 'contain' 'continue' 'control' 'cost' 'could' 'country' 'couple' 'course'
 'court' 'cover' 'create' 'crime' 'cultural' 'culture' 'cup' 'current'
 'customer' 'cut' 'dark' 'data' 'daughter' 'day' 'deal' 'debate' 'decade'
 'decide' 'decision' 'deep' 'defense' 'degree' 'democrat' 'democratic'
 'describe' 'design' 'despite' 'detail' 'determine' 'develop'
 'development' 'difference' 'different' 'difficult' 'dinner' 'direction'
 'director' 'discover' 'discuss' 'discussion' 'do' 'doctor' 'dog' 'door'
 'down' 'draw' 'dream' 'drive' 'drop' 'drug' 'during' 'each' 'early'
 'east' 'easy' 'eat' 'economic' 'economy' 'edge' 'education' 'effect'
 'effort' 'eight' 'either' 'election' 'else' 'employee' 'end' 'energy'
 'enjoy' 'enough' 'enter' 'entire' 'environment' 'environmental'
 'especially' 'establish' 'even' 'evening' 'event' 'ever' 'every'
 'everybody' 'everyone' 'everything' 'evidence' 'exactly' 'example'
 'executive' 'exist' 'expect' 'experience' 'expert' 'explain' 'eye' 'face'
 'fact' 'factor' 'fall' 'family' 'far' 'fast' 'father' 'fear' 'federal'
 'feel' 'feeling' 'few' 'field' 'fight' 'figure' 'fill' 'film' 'final'
 'finally' 'financial' 'find' 'fine' 'finish' 'fire' 'firm' 'first' 'fish'
 'five' 'floor' 'fly' 'focus' 'follow' 'food' 'foot' 'for' 'force'
 'foreign' 'forget' 'form' 'former' 'forward' 'four' 'free' 'friend'
 'from' 'front' 'full' 'fund' 'future' 'game' 'garden' 'gas' 'general'
 'generation' 'get' 'girl' 'give' 'glass' 'go' 'goal' 'good' 'government'
 'great' 'green' 'ground' 'group' 'grow' 'growth' 'guess' 'gun' 'guy'
 'hair' 'half' 'hand' 'happen' 'happy' 'hard' 'have' 'he' 'head' 'health'
 'hear' 'heart' 'heavy' 'help' 'her' 'here' 'herself' 'high' 'him'
 'himself' 'his' 'history' 'hit' 'hold' 'home' 'hope' 'hospital' 'hot'
 'hotel' 'hour' 'house' 'how' 'however' 'huge' 'human' 'hundred' 'husband'
 'idea' 'identify' 'if' 'image' 'imagine' 'impact' 'important' 'improve'
 'in' 'include' 'including' 'increase' 'indeed' 'indicate' 'individual'
 'industry' 'information' 'inside' 'instead' 'institution' 'interest'
 'interesting' 'international' 'interview' 'into' 'investment' 'involve'
 'issue' 'it' 'item' 'its' 'itself' 'job' 'join' 'just' 'keep' 'key' 'kid'
 'kind' 'kitchen' 'know' 'knowledge' 'land' 'language' 'large' 'last'
 'late' 'later' 'laugh' 'law' 'lawyer' 'lay' 'lead' 'leader' 'learn'
 'least' 'leave' 'left' 'leg' 'less' 'let' 'letter' 'level' 'life' 'light'
 'like' 'likely' 'line' 'list' 'listen' 'little' 'live' 'local' 'long'
 'look' 'lose' 'loss' 'lot' 'low' 'machine' 'magazine' 'main' 'maintain'
 'major' 'majority' 'make' 'man' 'manage' 'management' 'manager' 'many'
 'market' 'marriage' 'material' 'matter' 'may' 'maybe' 'me' 'mean'
 'measure' 'media' 'medical' 'meet' 'meeting' 'member' 'memory' 'mention'
 'message' 'method' 'middle' 'might' 'military' 'million' 'mind' 'minute'
 'miss' 'mission' 'model' 'modern' 'moment' 'money' 'month' 'more'
 'morning' 'most' 'mother' 'mouth' 'move' 'movement' 'movie' 'mr' 'mrs'
 'much' 'music' 'must' 'my' 'myself' 'name' 'nation' 'national' 'natural'
 'nature' 'near' 'nearly' 'necessary' 'need' 'network' 'never' 'new'
 'news' 'newspaper' 'next' 'nice' 'night' 'no' 'none' 'nor' 'north' 'not'
 'note' 'nothing' 'notice' 'now' 'number' 'occur' 'of' 'off' 'offer'
 'office' 'officer' 'official' 'often' 'oil' 'ok' 'old' 'on' 'once' 'one'
 'only' 'onto' 'open' 'operation' 'opportunity' 'option' 'or' 'order'
 'organization' 'other' 'others' 'our' 'out' 'outside' 'over' 'own'
 'owner' 'page' 'painting' 'paper' 'parent' 'part' 'participant'
 'particular' 'particularly' 'partner' 'party' 'pass' 'past' 'pattern'
 'pay' 'peace' 'people' 'per' 'perform' 'performance' 'perhaps' 'person'
 'personal' 'phone' 'physical' 'pick' 'picture' 'piece' 'place' 'plan'
 'plant' 'play' 'player' 'pm' 'point' 'police' 'policy' 'political'
 'politics' 'poor' 'popular' 'population' 'position' 'positive' 'possible'
 'power' 'practice' 'prepare' 'present' 'president' 'pressure' 'pretty'
 'prevent' 'price' 'probably' 'process' 'produce' 'product' 'production'
 'professional' 'professor' 'program' 'project' 'property' 'protect'
 'prove' 'provide' 'public' 'pull' 'purpose' 'push' 'put' 'quality'
 'question' 'quickly' 'quite' 'race' 'radio' 'raise' 'range' 'rate'
 'rather' 'reach' 'read' 'ready' 'real' 'reality' 'realize' 'really'
 'reason' 'receive' 'recent' 'recently' 'recognize' 'record' 'red'
 'reduce' 'reflect' 'region' 'relate' 'relationship' 'religious' 'remain'
 'remember' 'report' 'represent' 'republican' 'require' 'research'
 'resource' 'respond' 'response' 'responsibility' 'rest' 'result' 'return'
 'reveal' 'rich' 'right' 'rise' 'risk' 'road' 'rock' 'role' 'room' 'rule'
 'run' 'safe' 'same' 'save' 'say' 'scene' 'school' 'science' 'scientist'
 'score' 'sea' 'season' 'seat' 'second' 'section' 'security' 'see' 'seek'
 'seem' 'sell' 'send' 'senior' 'sense' 'series' 'serious' 'serve'
 'service' 'set' 'seven' 'several' 'shake' 'share' 'she' 'short' 'should'
 'shoulder' 'show' 'side' 'sign' 'significant' 'similar' 'simple' 'simply'
 'since' 'sing' 'single' 'sister' 'sit' 'site' 'situation' 'six' 'size'
 'skill' 'skin' 'small' 'smile' 'so' 'social' 'society' 'soldier' 'some'
 'somebody' 'someone' 'something' 'sometimes' 'son' 'song' 'soon' 'sort'
 'sound' 'source' 'south' 'southern' 'space' 'speak' 'special' 'specific'
 'speech' 'spend' 'sport' 'spring' 'staff' 'stage' 'stand' 'standard'
 'star' 'start' 'state' 'statement' 'station' 'stay' 'step' 'still'
 'stock' 'stop' 'store' 'story' 'strategy' 'street' 'strong' 'structure'
 'student' 'study' 'stuff' 'style' 'subject' 'success' 'successful' 'such'
 'suddenly' 'suffer' 'suggest' 'summer' 'support' 'sure' 'surface'
 'system' 'table' 'take' 'talk' 'task' 'tax' 'teach' 'teacher' 'team'
 'technology' 'television' 'tell' 'ten' 'tend' 'term' 'test' 'than'
 'thank' 'that' 'the' 'their' 'them' 'themselves' 'then' 'theory' 'there'
 'these' 'they' 'thing' 'think' 'third' 'this' 'those' 'though' 'thought'
 'thousand' 'threat' 'three' 'through' 'throughout' 'throw' 'thus' 'time'
 'to' 'today' 'together' 'tonight' 'too' 'top' 'total' 'tough' 'toward'
 'town' 'trade' 'traditional' 'training' 'travel' 'treat' 'treatment'
 'tree' 'trial' 'trip' 'trouble' 'true' 'truth' 'try' 'turn' 'tv' 'two'
 'type' 'under' 'understand' 'unit' 'until' 'up' 'upon' 'us' 'use'
 'usually' 'value' 'various' 'very' 'view' 'visit' 'voice' 'vote' 'wait'
 'walk' 'wall' 'want' 'war' 'watch' 'water' 'way' 'we' 'wear' 'week'
 'weight' 'well' 'west' 'western' 'what' 'whatever' 'when' 'where'
 'whether' 'which' 'while' 'white' 'who' 'whole' 'whom' 'whose' 'why'
 'wide' 'wife' 'will' 'win' 'wind' 'window' 'wish' 'with' 'within'
 'without' 'woman' 'wonder' 'word' 'work' 'worker' 'world' 'worry' 'would'
 'write' 'writer' 'wrong' 'yard' 'yeah' 'year' 'yes' 'yet' 'you' 'young'
 'your' 'yourself']

In [23]:
train_report = classification_report(ytrain,ypred)
print(train_report)

              precision    recall  f1-score   support

        fake       1.00      1.00      1.00      2024
        real       1.00      1.00      1.00      1976

    accuracy                           1.00      4000
   macro avg       1.00      1.00      1.00      4000
weighted avg       1.00      1.00      1.00      4000

In [24]:
test_report=classification_report(ytest,ypred_test)
print(test_report)

              precision    recall  f1-score   support

        fake       0.50      0.51      0.51      8032
        real       0.50      0.49      0.49      7968

    accuracy                           0.50     16000
   macro avg       0.50      0.50      0.50     16000
weighted avg       0.50      0.50      0.50     16000