# Ordinal Encoder

In [410]:
import pandas as pd 
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [411]:
df=pd.read_csv('categorical_regression_dataset.csv')

In [412]:
x=df.drop(columns='Salary')
y=df['Salary']

In [413]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [414]:
xtrain

   Experience_Level Education_Level Department
12         Beginner     High School    Finance
4      Intermediate     High School  Marketing
37         Beginner         Diploma    Finance
8          Advanced     High School         IT
3          Beginner          Master         IT
6      Intermediate        Bachelor      Sales
41     Intermediate         Diploma      Sales
46         Advanced        Bachelor      Sales
47         Advanced          Master    Finance
15         Beginner          Master         HR
9          Advanced         Diploma  Marketing
16     Intermediate     High School      Sales
24         Beginner     High School  Marketing
34         Advanced        Bachelor  Marketing
31     Intermediate          Master      Sales
0          Beginner     High School         HR
44         Advanced     High School  Marketing
27         Beginner          Master    Finance
33         Advanced         Diploma         IT
5      Intermediate         Diploma         HR
29     Intermediate         Diploma  Marketing
11         Advanced          Master      Sales
36         Beginner     High School      Sales
1          Beginner         Diploma      Sales
21         Advanced         Diploma      Sales
2          Beginner        Bachelor    Finance
43     Intermediate          Master         IT
35         Advanced          Master         HR
23         Advanced          Master         IT
40     Intermediate     High School         HR
10         Advanced        Bachelor         HR
22         Advanced        Bachelor    Finance
18     Intermediate        Bachelor         IT
49         Advanced          Master         IT
20         Advanced     High School         HR
7      Intermediate          Master    Finance
42     Intermediate        Bachelor    Finance
14         Beginner        Bachelor  Marketing
28     Intermediate     High School         IT
38         Beginner        Bachelor         IT

In [415]:
xtest

   Experience_Level Education_Level Department
13         Beginner         Diploma         IT
39         Beginner          Master  Marketing
30     Intermediate        Bachelor         HR
45         Advanced         Diploma         HR
17     Intermediate         Diploma    Finance
48     Intermediate        Bachelor  Marketing
26         Beginner        Bachelor      Sales
25         Beginner         Diploma         HR
32         Advanced     High School    Finance
19     Intermediate          Master  Marketing

In [416]:
# encoder=OrdinalEncoder(categories=[['Beginner','Intermediate','Advanced'],['High School','Diploma','Bachelor','Master'],['IT','HR','Marketing','Finance','Sales']])
# encoder=OrdinalEncoder(categories=[['Beginner','Intermediate','Advanced'],['High School','Diploma','Bachelor','Master'],['IT','HR','Marketing','Finance','Sales']],handle_unknown="error")
# encoder=OrdinalEncoder(categories=[['Beginner','Intermediate','Advanced'],['High School','Diploma','Bachelor','Master'],['IT','HR','Marketing','Finance','Sales']],handle_unknown='Use_encoded_value',unknown_value=-1)

In [417]:
encoder=OrdinalEncoder(categories=[['Beginner','Intermediate','Advanced'],['High School','Diploma','Bachelor','Master'],['IT','HR','Marketing','Finance','Sales']],handle_unknown="use_encoded_value",unknown_value=-1)
encoder.fit_transform(xtrain[['Experience_Level','Education_Level','Department']])
# encoder.transform([['Ohh','No','Yss']])

array([[0., 0., 3.],
       [1., 0., 2.],
       [0., 1., 3.],
       [2., 0., 0.],
       [0., 3., 0.],
       [1., 2., 4.],
       [1., 1., 4.],
       [2., 2., 4.],
       [2., 3., 3.],
       [0., 3., 1.],
       [2., 1., 2.],
       [1., 0., 4.],
       [0., 0., 2.],
       [2., 2., 2.],
       [1., 3., 4.],
       [0., 0., 1.],
       [2., 0., 2.],
       [0., 3., 3.],
       [2., 1., 0.],
       [1., 1., 1.],
       [1., 1., 2.],
       [2., 3., 4.],
       [0., 0., 4.],
       [0., 1., 4.],
       [2., 1., 4.],
       [0., 2., 3.],
       [1., 3., 0.],
       [2., 3., 1.],
       [2., 3., 0.],
       [1., 0., 1.],
       [2., 2., 1.],
       [2., 2., 3.],
       [1., 2., 0.],
       [2., 3., 0.],
       [2., 0., 1.],
       [1., 3., 3.],
       [1., 2., 3.],
       [0., 2., 2.],
       [1., 0., 0.],
       [0., 2., 0.]])

In [418]:
values=encoder.transform([['Ohh','No','Yss']])
print(values)

[[-1. -1. -1.]]

C:\Users\nasee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

In [419]:
df.head(50)

   Experience_Level Education_Level Department  Salary
0          Beginner     High School         HR   22000
1          Beginner         Diploma      Sales   24000
2          Beginner        Bachelor    Finance   26000
3          Beginner          Master         IT   28000
4      Intermediate     High School  Marketing   30000
5      Intermediate         Diploma         HR   32000
6      Intermediate        Bachelor      Sales   34000
7      Intermediate          Master    Finance   36000
8          Advanced     High School         IT   38000
9          Advanced         Diploma  Marketing   40000
10         Advanced        Bachelor         HR   42000
11         Advanced          Master      Sales   44000
12         Beginner     High School    Finance   23000
13         Beginner         Diploma         IT   25000
14         Beginner        Bachelor  Marketing   27000
15         Beginner          Master         HR   29000
16     Intermediate     High School      Sales   31000
17     Intermediate         Diploma    Finance   33000
18     Intermediate        Bachelor         IT   35000
19     Intermediate          Master  Marketing   37000
20         Advanced     High School         HR   39000
21         Advanced         Diploma      Sales   41000
22         Advanced        Bachelor    Finance   43000
23         Advanced          Master         IT   45000
24         Beginner     High School  Marketing   22500
25         Beginner         Diploma         HR   24500
26         Beginner        Bachelor      Sales   26500
27         Beginner          Master    Finance   28500
28     Intermediate     High School         IT   30500
29     Intermediate         Diploma  Marketing   32500
30     Intermediate        Bachelor         HR   34500
31     Intermediate          Master      Sales   36500
32         Advanced     High School    Finance   38500
33         Advanced         Diploma         IT   40500
34         Advanced        Bachelor  Marketing   42500
35         Advanced          Master         HR   44500
36         Beginner     High School      Sales   23500
37         Beginner         Diploma    Finance   25500
38         Beginner        Bachelor         IT   27500
39         Beginner          Master  Marketing   29500
40     Intermediate     High School         HR   31500
41     Intermediate         Diploma      Sales   33500
42     Intermediate        Bachelor    Finance   35500
43     Intermediate          Master         IT   37500
44         Advanced     High School  Marketing   39500
45         Advanced         Diploma         HR   41500
46         Advanced        Bachelor      Sales   43500
47         Advanced          Master    Finance   45500
48     Intermediate        Bachelor  Marketing   36500
49         Advanced          Master         IT   47000

In [420]:
encoder.transform(xtest[['Experience_Level','Education_Level','Department']])

array([[0., 1., 0.],
       [0., 3., 2.],
       [1., 2., 1.],
       [2., 1., 1.],
       [1., 1., 3.],
       [1., 2., 2.],
       [0., 2., 4.],
       [0., 1., 1.],
       [2., 0., 3.],
       [1., 3., 2.]])